apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ2YWxheHkxMjE4Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJVbUZxZFRwQmNtaGhRREV5TVRrPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson